// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayServices
{
        public const string achievement_jump_into_ten_minecarts = "CgkIkpS4ssAEEAIQAg"; // <GPGSID>
        public const string achievement_run_5000m = "CgkIkpS4ssAEEAIQBg"; // <GPGSID>
        public const string leaderboard_time_jumper_leaderboard = "CgkIkpS4ssAEEAIQAQ"; // <GPGSID>
        public const string achievement_run_a_total_of_5000m = "CgkIkpS4ssAEEAIQBA"; // <GPGSID>
        public const string achievement_run_a_total_of_10000m = "CgkIkpS4ssAEEAIQBQ"; // <GPGSID>
        public const string achievement_run_2000m = "CgkIkpS4ssAEEAIQAw"; // <GPGSID>

}

